spring.application.name=mtg-deck-assistant
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=stone
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=5000,expireAfterWrite=7d