CREATE TABLE decks
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    format            VARCHAR(255) NOT NULL,
    name              VARCHAR(100) NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    commander_slot_id BIGINT,

    CONSTRAINT decks_format_check
        CHECK (format IN (
                          'COMMANDER',
                          'STANDARD',
                          'MODERN',
                          'PRERELEASE',
                          'SEALED',
                          'DRAFT'
            )),

    CONSTRAINT uk_decks_commander_slot
        UNIQUE (commander_slot_id)
);

CREATE TABLE deck_slots
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_name VARCHAR(255) NOT NULL,
    qty       INTEGER NOT NULL,
    deck_id   BIGINT NOT NULL,

    CONSTRAINT uk_deck_card
        UNIQUE (deck_id, card_name),

    CONSTRAINT fk_deck_slots_deck
        FOREIGN KEY (deck_id)
            REFERENCES decks(id)
);

ALTER TABLE decks
    ADD CONSTRAINT fk_decks_commander_slot
        FOREIGN KEY (commander_slot_id)
            REFERENCES deck_slots(id);